version: "{build}"

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 4
    - nodejs_version: 6
    - nodejs_version: 8

install:
  - ps: Install-Product node $env:nodejs_version
  - npm cache clean
  - npm install

build: off

test_script:
  - npm test

cache:
  - node_modules

matrix:
  fast_finish: true
